In [1]:
import numpy as np 
import pandas as pd 
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import sklearn.model_selection as skmodel
import matplotlib.pyplot as plt
from sklearn import datasets

C:\Users\Dagher\AppData\Local\Temp\ipykernel_3212\451727892.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
dataframe = pd.read_csv("combined_dataset_revised.csv")

In [3]:
# divide data into attributes and save the last column as classification label

attributes = ['is_above_35','is_below_18','is_between_25_and_35','is_between_18_and_24','enjoys_crowded','enjoys_nightlife','enjoys_outdoor','enjoys_nature','enjoys_museums_and_galleries','enjoys_culture_and_education','enjoys_books','is_religious','enjoys_calm','is_spritual','enjoys_self_care','enjoys_clothes_shopping','enjoys_physical_exercise','enjoys_sports','enjoys_restaurants','enjoys_grocery_shopping','hates_shopping','prefers_delivery','enjoys_movie_nights', 'likes_animals']

attribute_list = dataframe[attributes]
classification_label = dataframe['in_a_relationship']

In [4]:
attribute_train, attribute_test, class_train, class_test = skmodel.train_test_split(attribute_list, classification_label, test_size = 0.2, random_state= 0)

In [11]:
decision_tree = DecisionTreeClassifier().fit(attribute_train, class_train) 
class_names_str = classification_label.astype(str).unique()
scores = skmodel.cross_val_score(decision_tree, attribute_list, classification_label, cv=10)

value = scores.mean()

response = decision_tree.predict([['0','0','0','1','4','5','4','5','2','3','1','5','3','3','4','2','4','4','4','3','4','3','5','5'], #1
                                  ['0','0','0','1','3','2','5','5','5','5','5','4','4','3','4','3','5','5','4','5','5','3','4','5'], #1
                                  ['0','0','1','0','2','5','5','5','3','2','3','5','5','4','3','4','4','4','4','2','3','1','2','5'], #0
                                  ['0','0','0','1','2','4','3','5','4','4','5','1','4','4','4','3','4','4','3','2','3','3','5','3']]) #0
          
text_representation = tree.export_text(decision_tree)
# print(text_representation)
# print(response)
dataframe.iloc[0:30, :]
# fig = plt.figure(figsize=(25,20))
# _=tree.plot_tree(decision_tree, feature_names= attributes, class_names=class_names_str, filled=True)
# plt.show()

c:\Users\Dagher\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

,is_above_35,is_below_18,is_between_25_and_35,is_between_18_and_24,enjoys_crowded,enjoys_nightlife,enjoys_outdoor,enjoys_nature,enjoys_museums_and_galleries,enjoys_culture_and_education,...,enjoys_clothes_shopping,enjoys_physical_exercise,enjoys_sports,enjoys_restaurants,enjoys_grocery_shopping,hates_shopping,prefers_delivery,enjoys_movie_nights,likes_animals,in_a_relationship
0,0,0,0,1,4,5,4,5,2,3,...,2,4,4,4,3,4,3,5,5,1
1,0,0,0,1,3,2,5,5,5,5,...,3,5,5,4,5,5,3,4,5,1
2,0,0,1,0,2,5,5,5,3,2,...,4,4,4,4,2,3,1,2,5,0
3,0,0,0,1,2,4,3,5,4,4,...,3,4,4,3,2,3,3,5,3,0
4,0,0,0,1,2,5,3,5,1,3,...,3,3,4,5,4,3,4,4,5,0
5,0,0,0,1,2,1,4,3,3,4,...,4,4,4,5,3,2,3,4,1,0
6,0,0,0,1,2,1,1,2,2,2,...,3,5,4,4,4,1,1,5,4,0
7,0,0,0,1,5,5,5,5,3,5,...,1,5,5,5,1,1,1,5,5,1
8,0,0,0,1,3,4,3,5,3,5,...,2,4,5,4,1,4,2,4,3,1
9,0,0,0,1,1,1,5,5,3,5,...,2,5,5,5,3,1,1,5,5,0
10,0,0,1,0,1,3,4,5,1,3,...,3,5,5,3,3,5,5,5,5,0
11,0,0,0,1,3,3,3,3,3,3,...,2,4,4,5,5,5,5,5,5,1
12,0,0,0,1,2,5,5,5,5,3,...,5,5,5,4,5,1,4,5,5,1
13,0,0,1,0,3,4,4,4,4,5,...,5,5,5,5,3,1,1,4,2,1
14,0,0,0,1,3,1,4,5,3,4,...,2,3,3,2,4,2,4,2,5,0
15,0,0,1,0,2,2,2,5,5,5,...,4,5,5,5,5,1,1,5,5,0
16,0,0,0,1,3,5,4,4,3,4,...,3,5,5,5,3,4,3,4,5,1
17,0,0,1,0,3,3,3,5,4,4,...,1,5,5,3,3,2,2,3,5,0
18,0,0,1,0,3,4,4,4,3,4,...,5,4,4,4,4,1,3,4,5,1
19,0,0,0,1,2,4,4,5,4,5,...,1,4,3,2,1,4,3,4,5,0
20,0,0,0,1,5,5,5,5,5,4,...,3,4,4,5,4,2,1,5,3,1
21,0,0,0,1,2,3,2,5,3,3,...,3,5,3,3,3,1,5,5,5,0
22,0,0,0,1,3,4,4,5,5,5,...,4,5,4,5,4,3,3,5,5,1
23,0,0,0,1,1,1,1,3,1,3,...,5,5,5,5,5,1,5,5,5,0
24,0,0,1,0,3,2,4,3,2,4,...,2,5,5,4,2,2,1,4,5,1
25,0,0,1,0,5,3,2,3,1,5,...,1,5,5,3,1,3,1,5,5,1
26,0,0,1,0,4,5,5,5,1,3,...,4,4,5,3,3,2,3,4,4,1
27,0,0,0,1,3,5,4,5,1,5,...,5,5,5,5,5,1,1,5,5,0
28,0,0,0,1,3,1,3,5,3,3,...,1,5,5,5,5,1,1,3,5,1
29,0,0,0,1,1,1,2,4,4,4,...,2,5,5,3,1,4,4,3,4,0